-- liquibase formatted sql

-- changeset EvgenyF:1

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR,
    first_name    VARCHAR,
    last_name     VARCHAR,
    phone         VARCHAR,
    reg_date      VARCHAR,
    city          VARCHAR,
    password      VARCHAR,
    image         VARCHAR
);



-- changeset GlebD:2
CREATE TABLE ads
(
    pk          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR,
    title VARCHAR,
    user_id BIGINT REFERENCES users (id),
    price BIGINT
);

-- changeset GlebD:3

CREATE TABLE image
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path VARCHAR,
    file_size BIGINT,
    media_type VARCHAR,
    data BYTEA,
    ads_pk BIGINT REFERENCES ads (pk)
);

