--liquibase formatted sql
--changeset EvgenyF:1
create table ads
(
    pk           int8 generated by default as identity,
    description  varchar(255),
    price        int8,
    title        varchar(255),
    user_info_id int8,
    primary key (pk)
);
create table avatars
(
    id           int8 generated by default as identity,
    data         bytea,
    file_path    varchar(255),
    file_size    int8,
    media_type   varchar(255),
    user_info_id int8,
    primary key (id)
);
create table comments
(
    pk           int8 generated by default as identity,
    created_at   varchar(255),
    text         varchar(255),
    user_info_id int8,
    ads_pk     int8,
    primary key (pk)
);
create table image
(
    id         int8 generated by default as identity,
    data       bytea,
    file_path  varchar(255),
    file_size  int8,
    media_type varchar(255),
    ads_pk     int8,
    primary key (id)
);
create table users_info
(
    id         int8 generated by default as identity,
    city       varchar(255),
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    phone      varchar(255),
    reg_date   varchar(255),
    primary key (id)
);
alter table if exists ads
    add constraint FKi519na06kjtjdjjkl6ig338oo foreign key (user_info_id) references users_info;
alter table if exists avatars
    add constraint FK8q3t54ga7fuqhoa7xgg4x00jw foreign key (user_info_id) references users_info;
alter table if exists comments
    add constraint FK134qw14wbenh6l0vwjre89dp foreign key (user_info_id) references users_info;
alter table if exists image
    add constraint FK4j3wycmqde3krjyn3icsgqjf7 foreign key (ads_pk) references ads;

create table users
(
    username varchar(255),
    password varchar(255),
    enabled boolean,
primary key (username)
);
alter table users_info add  foreign key (email) references users;
create  table authorities
(username varchar(255),
authority varchar(255),
foreign key (username) references users
);
--changeset EvgenyF:2
alter table users_info add column image text;
alter table users_info drop column image;




